"use strict";
let num = 10;
// console.log(num);
console.log("Arithmetic Compound Operators:");
console.log("Addition");
num += 5;
console.log(num);
console.log("Subtraction");
num -= 3;
console.log(num);
console.log("Multiplication");
num *= 2;
console.log(num);
console.log("Division");
num /= 4;
console.log(num);
